name: Build TigerVNC Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Раскомментируйте для ручного запуска:
  # workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: tigervnc:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true  # Сохраняем образ для тестирования
        
    - name: Test the image - VNC Viewer version
      run: |
        docker run --rm tigervnc:latest vncviewer --version
        
    - name: Test the image - List files
      run: |
        docker run --rm tigervnc:latest ls -la /opt/tigervnc/bin/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-image-info
        path: |
          Dockerfile
        retention-days: 30